[project]
name = "testchess"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "flash>=1.0.3",
    "flask>=3.1.0",
    "jsonfy>=0.4",
    "python-chess>=1.999",
    "stockfish>=3.28.0",
]
