name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-analyze:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install uv and stockfish
      run: |
        pip install uv
        sudo apt-get update
        sudo apt-get install -y stockfish

    - name: Create virtualenv and install dependencies
      run: |
        uv venv
        source .venv/bin/activate
        uv add pytest mypy
        uv add flask
        uv pip install .

    - name: Run tests
      run: |
        source .venv/bin/activate
        pytest

    - name: Run mypy
      run: |
        source .venv/bin/activate
        mypy --disable-error-code import-untyped .
